<?php

namespace Gatsun\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireLiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireLiveRepository extends EntityRepository
{
	public function getCommentaires()
	{
		$date = new \DateTime("yesterday 14:00");
		$qb = $this->_em->createQueryBuilder();

		$qb->select('a')
		   ->from('GatsunWebsiteBundle:CommentaireLive', 'a')
		   ->where('a.date > :date')
		   ->orderBy('a.date', 'DESC')
		   ->setParameter('date', $date, \Doctrine\DBAL\Types\Type::DATETIME);

		return $qb->getQuery()
				  ->getResult();
	}
}
