<?php

namespace Gatsun\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
	public function getPodcasts()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('a')
		   ->from('GatsunWebsiteBundle:Publication', 'a')
		   ->where('a.podcast != \'\'')
		   ->orderBy('a.id', 'DESC')
		   ->setMaxResults(6);

		return $qb->getQuery()
				  ->getResult();
	}
}
