<?php

namespace Gatsun\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VignetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VignetteRepository extends EntityRepository
{
}
